# Generated by Django 6.0.4 on 2026-05-02 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_officelocation_radius_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shift_end",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
