# Generated by Django 6.0.4 on 2026-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_shift_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.UniqueConstraint(
                fields=("user", "start_date", "end_date"), name="unique_leave_request"
            ),
        ),
    ]
